title: My Portfolio
description: A collection of my work as a Shopify Developer
url: "http://127.0.0.1:4000" # Local URL
baseurl: "" # Root directory
permalink: /:year/:month/:day/:title/ # URL structure for posts

markdown: kramdown # Defines markdown processor
