---
layout: null
---
/**
 * Service Worker for Portfolio Site
 * Provides offline support and caching for improved performance
 * Paths are generated by Jekyll based on site.baseurl
 */

const CACHE_NAME = "portfolio-v2";
const RUNTIME_CACHE = "portfolio-runtime-v2";

// Assets to cache immediately on install (paths use site.baseurl from Jekyll)
const PRECACHE_ASSETS = [
  "{{ site.baseurl }}/",
  "{{ site.baseurl }}/index.html",
  "{{ site.baseurl }}/about.html",
  "{{ site.baseurl }}/work.html",
  "{{ site.baseurl }}/services.html",
  "{{ site.baseurl }}/contact.html",
  "{{ site.baseurl }}/rates.html",
  "{{ site.baseurl }}/styles/style.css",
  "{{ site.baseurl }}/styles/index.css",
  "{{ site.baseurl }}/styles/header.css",
  "{{ site.baseurl }}/styles/footer.css",
  "{{ site.baseurl }}/styles/variables.css",
  "{{ site.baseurl }}/styles/client-work.css",
  "{{ site.baseurl }}/styles/work.css",
  "{{ site.baseurl }}/styles/about.css",
  "{{ site.baseurl }}/scripts/scripts.js",
  "{{ site.baseurl }}/images/logos/logo-white-small.jpg",
  "{{ site.baseurl }}/images/profile-picture.jpeg"
];

// Install event - cache essential assets
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(PRECACHE_ASSETS).catch((error) => {
        console.warn("Failed to cache some assets:", error);
      });
    })
  );
  self.skipWaiting();
});

// Activate event - clean up old caches
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((cacheName) => {
            return cacheName !== CACHE_NAME && cacheName !== RUNTIME_CACHE;
          })
          .map((cacheName) => {
            return caches.delete(cacheName);
          })
      );
    })
  );
  self.clients.claim();
});

// Fetch event - network-first for HTML (always fresh), cache-first for assets
self.addEventListener("fetch", (event) => {
  // Skip non-GET requests
  if (event.request.method !== "GET") {
    return;
  }

  // Skip cross-origin requests
  if (!event.request.url.startsWith(self.location.origin)) {
    return;
  }

  // Navigation requests (HTML pages) - network first, fallback to cache
  // This ensures users always get fresh content when refreshing
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          const responseToCache = response.clone();
          caches.open(RUNTIME_CACHE).then((cache) => {
            cache.put(event.request, responseToCache);
          });
          return response;
        })
        .catch(() => caches.match(event.request).then((cached) => cached || caches.match("{{ site.baseurl }}/index.html")))
    );
    return;
  }

  // Assets (CSS, JS, images) - cache first, fallback to network
  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }
      return fetch(event.request).then((response) => {
        if (!response || response.status !== 200 || response.type !== "basic") {
          return response;
        }
        const responseToCache = response.clone();
        caches.open(RUNTIME_CACHE).then((cache) => {
          cache.put(event.request, responseToCache);
        });
        return response;
      });
    })
  );
});
